module.exports = [
// LED stripe
    { ChStatus: "active", ChType: "actuator",ChAlias: "antex-stripe",  ChMeas: "status", SourceName: "ANTEX",    DeviceId: "led",     ChNum: 0,  DeviceHash: "a3f7-2c9e-5b1d-8e46", Address: "", Config: {}, ValueType: "string" },
// KSC ports
    { ChStatus: "active", ChType: "actuator",ChAlias: "port1",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 16, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port2",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 17, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port3",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 18, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port4",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 19, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port5",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 20, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port6",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 21, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port7",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 22, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port8",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 23, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port9",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 24, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port10",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 25, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port11",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 26, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port12",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 27, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port13",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 28, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port14",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 29, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port15",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 30, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "actuator",ChAlias: "port16",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "adampost",ChNum: 31, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
// KCS sensors
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp1",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 0,  DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp2",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 1,  DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp3",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 2,  DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp4",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 3,  DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp5",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 4,  DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp6",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 5,  DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp7",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 6,  DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp8",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 7,  DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp9",         ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 8,  DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp10",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 9,  DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp11",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 10, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp12",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 11, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp13",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 12, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp14",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 13, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp15",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 14, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "tamp16",        ChMeas: "status", SourceName: "KCS-04",   DeviceId: "kcs-post",ChNum: 15, DeviceHash: "7c4d-9f2a-6e8b-1c37", Address: "", Config: {} },
// RealLab NSL
    { ChStatus: "active", ChType: "sensor",  ChAlias: "nls-04-input",  ChMeas: "status", SourceName: "NLS-04",   DeviceId: "nls04",   ChNum: 0,  DeviceHash: "f5e2-0b8c-4d1a-9f63", Address: "", Config: {}, ValueType: "string" },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "nls-04-vout",   ChMeas: "V",      SourceName: "NLS-04",   DeviceId: "nls04",   ChNum: 1,  DeviceHash: "f5e2-0b8c-4d1a-9f63", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "nls-04-iout",   ChMeas: "A",      SourceName: "NLS-04",   DeviceId: "nls04",   ChNum: 2,  DeviceHash: "f5e2-0b8c-4d1a-9f63", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "nls-04-vacc",   ChMeas: "V",      SourceName: "NLS-04",   DeviceId: "nls04",   ChNum: 3,  DeviceHash: "f5e2-0b8c-4d1a-9f63", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "nls-04-temp",   ChMeas: "C",      SourceName: "NLS-04",   DeviceId: "nls04",   ChNum: 4,  DeviceHash: "f5e2-0b8c-4d1a-9f63", Address: "", Config: {} },
    { ChStatus: "active", ChType: "sensor",  ChAlias: "nls-04-outp",   ChMeas: "status", SourceName: "NLS-04",   DeviceId: "nls04",   ChNum: 5,  DeviceHash: "f5e2-0b8c-4d1a-9f63", Address: "", Config: {}, ValueType: "string" }
];