module.exports = [
        // Primary services
	{ Name: "process",         Status: 'stopped', ErrorMsg: '', Service: null, Importance: "primary",    InitOrder: 10,  Protocol: 'sys',       PrimaryBus: 'sysBus',       BusList: ['logBus', 'mdbBus', 'dataBus'],                                EventList: ['process-config-system-get', 'process-ws-connect-done', 'process-mqtt-connect-done', 'process-rpi-connect-done'], AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'Process desription'},
        { Name: "providermdb",     Status: 'stopped', ErrorMsg: '', Service: null, Importance: "primary",    InitOrder: 20,  Protocol: 'sys',       PrimaryBus: 'mdbBus',       BusList: ['logBus', 'sysBus'],                                           EventList: ['event1', 'event2', 'event3', 'event4'],                                                                          AdvancedOptions: {},                                                                        Dependency: ['srvService', 'mongodb'],  Description: 'Provider desription'},
        { Name: "logger",          Status: 'stopped', ErrorMsg: '', Service: null, Importance: "primary",    InitOrder: 30,  Protocol: 'sys',       PrimaryBus: 'logBus',       BusList: ['sysBus', 'mdbBus', 'dataBus', 'rpiBus', 'lhpBus', 'mqttBus'], EventList: ['logger-log', 'all-init-stage1-set'],                                                                             AdvancedOptions: {host: '10.110.71.231', port: 5142, hostname: 'HUB-Low',  console: false}, Dependency: ['srvService', 'graylog2'], Description: 'Logger desription'},
        { Name: "proxylogger",     Status: 'stopped', ErrorMsg: '', Service: null, Importance: "primary",    InitOrder: 31,  Protocol: 'sys',       PrimaryBus: 'logBus',       BusList: ['sysBus', 'mdbBus', 'dataBus', 'rpiBus', 'lhpBus', 'mqttBus'], EventList: ['logger-log', 'all-init-stage1-set'],                                                                             AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'Proxy logger desription'},
        { Name: "proxychannel",    Status: 'stopped', ErrorMsg: '', Service: null, Importance: "primary",    InitOrder: 32,  Protocol: 'sys',       PrimaryBus: 'dataBus',      BusList: ['sysBus', 'dataBus', 'logBus'],                                EventList: ['all-init-stage1-set'],                                                                                           AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'Proxy channel desription'},
        { Name: "dm",              Status: 'stopped', ErrorMsg: '', Service: null, Importance: "primary",    InitOrder: 40,  Protocol: 'sys',       PrimaryBus: 'sysBus',       BusList: ['logBus', 'mdbBus', 'dataBus'],                                EventList: ['all-init-stage1-set', 'all-close', 'all-connections-done', 'mqttclient-send'],                                   AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'Device Manager desription'},

        // Auxilary services
        { Name: "modbusclienttcp", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary",   InitOrder: 100, Protocol: 'modbustcp', PrimaryBus: 'modbustcpBus', BusList: ['logBus', 'sysBus'],                                           EventList: ['all-init-stage1-set', 'test-connect', 'all-disconnect', 'modbusclienttcp-send'],                                 AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'Modbus client desription'},
        { Name: "proxymodbustcp",  Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary",   InitOrder: 110, Protocol: 'modbustcp', PrimaryBus: 'modbustcpBus', BusList: ['logBus', 'sysBus'],                                           EventList: ['all-init-stage1-set', 'test-connect', 'proxymodbustcp-msg-get', 'proxymodbustcp-msg-get'],                       AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'ProxyModbus desription'},

	{ Name: "modbusclientrot", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary",   InitOrder: 120, Protocol: 'modbusrot', PrimaryBus: 'modbusrotBus', BusList: ['logBus', 'sysBus'],                                           EventList: ['all-init-stage1-set', 'test-connect', 'all-disconnect', 'modbusclientrot-send', 'modbusled-source-toss'],        AdvancedOptions: {},                                                                        Dependency: ['srvModbusBase'],          Description: 'Modbus client desription'},
        { Name: "proxymodbusrot",  Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary",   InitOrder: 130, Protocol: 'modbusrot', PrimaryBus: 'modbusrotBus', BusList: ['logBus', 'sysBus'],                                           EventList: ['all-init-stage1-set', 'test-connect', 'proxymodbusrot-msg-get', 'proxymodbusrot-msg-get'],                       AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'ProxyModbus desription'},

        { Name: "snmpclient",      Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary",   InitOrder: 140, Protocol: 'snmp',      PrimaryBus: 'snmpBus',      BusList: ['logBus', 'sysBus'],                                           EventList: ['all-init-stage1-set', 'test-connect', 'all-disconnect', 'snmpclient-send'],                                      AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'SNMP client desription'},
        { Name: "proxysnmp",       Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary",   InitOrder: 150, Protocol: 'snmp',      PrimaryBus: 'snmpBus',      BusList: ['logBus', 'sysBus'],                                           EventList: ['all-init-stage1-set', 'test-connect', 'proxysnmp-msg-get', 'proxysnmp-msg-get'],                                 AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'ProxySNMP desription'},

        // Exploitary services
	{ Name: "modbusled",       Status: 'stopped', ErrorMsg: '', Service: null, Importance: "exploitary", InitOrder: 500, Protocol: 'mled',      PrimaryBus: 'modbusledBus', BusList: ['logBus', 'sysBus', 'modbusrotBus'],                           EventList: ['all-init-stage1-set', 'test-connect', 'all-disconnect', 'modbusclientrot-send'],                                 AdvancedOptions: {host: 'modbusclientrot'},                                                 Dependency: ['srvService'],             Description: 'ModbusLED client desription'},
        { Name: "proxymodbusled",  Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary",   InitOrder: 510, Protocol: 'mled',      PrimaryBus: 'modbusledBus', BusList: ['logBus', 'sysBus'],                                           EventList: ['all-init-stage1-set', 'test-connect', 'proxymodbusled-msg-get'],                                                 AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'ProxyModbusLED desription'},

        { Name: "modbusDRS",       Status: 'stopped', ErrorMsg: '', Service: null, Importance: "exploitary", InitOrder: 520, Protocol: 'mbdrs',     PrimaryBus: 'modbusdrsBus', BusList: ['logBus', 'sysBus', 'modbusrotBus'],                           EventList: ['all-init-stage1-set', 'test-connect', 'all-disconnect', 'modbusclientrot-send', 'modbusdrs-msg-get'],            AdvancedOptions: {host: 'modbusclientrot'},                                                 Dependency: ['srvService'],             Description: 'ModbusMWDRS240 client desription'},
        { Name: "proxymodbusdrs",  Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary",   InitOrder: 530, Protocol: 'mbdrs',     PrimaryBus: 'modbusdrsBus', BusList: ['logBus', 'sysBus'],                                           EventList: ['all-init-stage1-set', 'test-connect', 'proxymodbusdrs-msg-get'],                                                 AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'ProxyModbusDRS desription'},

        { Name: "modbusNLS",       Status: 'stopped', ErrorMsg: '', Service: null, Importance: "exploitary", InitOrder: 540, Protocol: 'mbnls',     PrimaryBus: 'modbusnlsBus', BusList: ['logBus', 'sysBus', 'modbusrotBus'],                           EventList: ['all-init-stage1-set', 'test-connect', 'all-disconnect', 'modbusclientrot-send', 'modbusnls-msg-get'],            AdvancedOptions: {host: 'modbusclientrot'},                                                 Dependency: ['srvService'],             Description: 'ModbusRLNLS client desription'},
        { Name: "proxymodbusnls",  Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary",   InitOrder: 550, Protocol: 'mbnls',     PrimaryBus: 'modbusnlsBus', BusList: ['logBus', 'sysBus'],                                           EventList: ['all-init-stage1-set', 'test-connect', 'proxymodbusnls-msg-get'],                                                 AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'ProxyModbusNLS desription'},

        { Name: "modbusKCS",       Status: 'stopped', ErrorMsg: '', Service: null, Importance: "exploitary", InitOrder: 560, Protocol: 'mbkcs',     PrimaryBus: 'modbuskcsBus', BusList: ['logBus', 'sysBus', 'modbusrotBus'],                           EventList: ['all-init-stage1-set', 'test-connect', 'all-disconnect', 'modbusclientrot-send', 'modbuskcs-msg-get'],            AdvancedOptions: {host: 'modbusclientrot'},                                                 Dependency: ['srvService'],             Description: 'ModbusKCS client desription'},
        { Name: "proxymodbuskcs",  Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary",   InitOrder: 570, Protocol: 'mbkcs',     PrimaryBus: 'modbuskcsBus', BusList: ['logBus', 'sysBus'],                                           EventList: ['all-init-stage1-set', 'test-connect', 'proxymodbuskcs-msg-get'],                                                 AdvancedOptions: {},                                                                        Dependency: ['srvService'],             Description: 'ProxyModbusKCS desription'}
];       